{
 "title": "Grafana Report",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "g",
    "label": "granularity",
    "query": "1s,2s,5s,10s,30s,1m,2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "duration_1", "query": "800" },
   { "name": "duration_2", "query": "1200" },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": "SELECT DISTINCT(\"simulation\") FROM (\n    SELECT \"simulation\",\"mean\" \n    FROM \"$archive\".\"gatling\" \n    WHERE $timeFilter)\n--SELECT \"simulation\" FROM (SELECT last(\"mean\") from \"gatling\" WHERE $timeFilter GROUP BY \"simulation\")"
   },
   {
    "name": "run",
    "label": "Run",
    "query": "SELECT \"run\" FROM (SELECT last(\"mean\") from \"$archive\".\"gatling\" WHERE \"run\" <> '' AND \"simulation\" =~ /^$simulation$/ AND $timeFilter GROUP BY \"run\")"
   },
   {
    "name": "host",
    "label": "Load Station",
    "query": "SELECT \"host\" FROM \n(SELECT last(\"mean\") from \"$archive\".\"gatling\" WHERE \"run\" =~ /^${run:regex}$/ AND \"simulation\" =~ /^${simulation:regex}$/ AND $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "group1",
    "label": "Group (level 1)",
    "query": "SELECT \"group1\" FROM (select last(\"mean\") from \"$archive\".gatling where (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND \"simulation\" = '$simulation' AND \"group\"='1' AND $timeFilter GROUP BY \"group1\")"
   },
   {
    "name": "group2",
    "label": "Group (level 2)",
    "query": "SELECT \"group2\" FROM (select last(\"mean\") from \"$archive\".gatling where (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND \"simulation\" =~ /^$simulation$/ AND \"group1\" =~ /^$group1$/ AND \"group\"='2' AND $timeFilter GROUP BY \"group2\")"
   },
   {
    "name": "group3",
    "label": "Group (level 3)",
    "query": "SELECT \"group3\" FROM (select last(\"mean\") from \"$archive\".gatling where (\"run\" =~ /^${run:regex}$/ OR \"run\" = '') AND (\"host\" =~ /^${host:regex}$/ OR \"host\" = '') AND \"simulation\" =~ /^${simulation:regex}$/ AND \"group1\" =~ /^${group1:regex}$/ AND \"group2\" =~ /^${group2:regex}$/ AND \"group\"='3' AND $timeFilter GROUP BY \"group3\")"
   },
   {
    "name": "request",
    "label": "Request",
    "query": "SELECT \"request\" FROM (select last(\"mean\") from \"$archive\".gatling where (\"run\" =~ /^${run:regex}$/ OR \"run\" = '') AND (\"host\" =~ /^${host:regex}$/ OR \"host\" = '') AND \"simulation\" =~ /^${simulation:regex}$/ AND \"request\" != 'allRequests' AND $timeFilter AND (\"group\" = '0' OR \"group\" = '' OR (\"group\" = '1' AND \"group1\" =~ /^${group1:regex}$/) OR (\"group\" = '2' AND \"group1\" =~ /^${group1:regex}$/ AND \"group2\" =~ /^${group2:regex}$/) OR (\"group\" <> '' AND \"group\" <> '1' AND \"group\" <> '2' AND \"group1\" =~ /^${group1:regex}$/ AND \"group2\" =~ /^${group2:regex}$/ AND \"group3\" =~ /^${group3:regex}$/) )  GROUP BY \"request\") "
   },
   {
    "name": "scenario",
    "label": "User (Scenario)",
    "query": "SHOW TAG VALUES  FROM \"gatling.users\" WITH KEY = \"request\" where (\"run\" =~ /^${run:regex}$/ OR \"run\" = '') AND (\"host\" =~ /^${host:regex}$/ OR \"host\" = '')  AND \"simulation\" =~ /^${simulation:regex}$/ AND \"request\" != 'allUsers' AND $timeFilter"
   },
   {
    "name": "Total",
    "label": "Total",
    "query": "SELECT max(\"X\") FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"status\" = 'all' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') AND (\"host\" =~ /^$host$/ or \"host\"='')), (SELECT last(\"count\")-last(\"count\")+0.00001 as \"X\" FROM \"$archive\".gatling)\n\n-- default value is 0.00001"
   },
   {
    "name": "gatlingWriteDuration",
    "label": "gatlingWriteDuration",
    "query": "SELECT max(\"X\") FROM (SELECT percentile(\"E\", 90) as \"X\" FROM (SELECT ELAPSED(\"count\", 1s) as \"E\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/) and $timeFilter and \"status\" = 'all' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') AND (\"host\" =~ /^$host$/ or \"host\"=''))), (SELECT last(\"count\")-last(\"count\")+0 as \"X\" FROM \"$archive\".gatling)\n\n-- default value of gatlingWriteDuration = 0"
   },
   {
    "name": "testDuration",
    "label": "testDuration",
    "query": "SELECT max(\"E2\")+$gatlingWriteDuration FROM (SELECT sum(\"E\") as \"E2\" FROM (select ELAPSED(\"count\", 1s) as \"E\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/) and $timeFilter and \"status\" = 'all' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') AND (\"host\" =~ /^$host$/ or \"host\"='') GROUP BY \"host\") GROUP BY \"host\"), (SELECT last(\"count\")-last(\"count\")+0    as \"E2\" FROM \"$archive\".gatling)\n\n-- default value: 0"
   },
   {
    "name": "testDurationX2",
    "label": "testDurationX2",
    "query": "SELECT ((\"zero\" + $testDuration) * 2) FROM (SELECT last(\"count\")-last(\"count\") as \"zero\" from \"$archive\".\"gatling\")\n\n-- default value: 0"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Run Links for simulation: $simulation",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "simulation" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT (last(\"duration\")*2+10) as \"Duration\" from (SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) as \"duration\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY time(10s),  \"run\") GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "elapsed" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"X\") as \"writeInterval\" from (SELECT percentile(\"E\", 90) as \"X\" FROM (SELECT ELAPSED(\"count\", 1s) as \"E\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/) and $timeFilter and \"status\" = 'all' and \"request\" = 'allRequests')  GROUP BY time(10s), \"run\") GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gatling",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "content": "<div style=\"font-weight: bold; float: right; padding: 0; margin: 0; position: absolute; right: 0; z-index: -1; padding: 7px 50px; margin: 5px 5px 0 5px; font-size: 28px;\">\n<div>Simulation: <span style=\"color: #e37400;\">$simulation</span></div>\n</div>\n\n<div style=\"font-weight: bold; float: right; padding: 0; margin: 0; position: absolute; right: 0; z-index: -1; padding: 7px 50px; margin: 5px 5px 0 5px; font-size: 20px;\">\nRun: <span style=\"color: #e37400;\">$run</span>;\nLoad station(s): <span style=\"color: #e37400;\">$host</span>;\nduration: <span style=\"color: #e37400;\">$testDuration seconds</span>;\n</div>\n\n\n<div style=\"border-bottom: 7px #E37400 solid; padding: 10px 0 5px 0; margin: 0 5px; z-index: -1;\">\n<div style=\"background: #e37400; color: #fff; font-weight: bold; display: inline; margin: 0 10px 0 0; padding: 5px 15px 5px 25px; border-top-right-radius: 8px; border-top-left-radius: 8px; font-size: 14px;\">GLOBAL</div>\n</div>\n"
    }
   ]
  },
  {
   "title": "Global Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
     "content": "<div style=\"color: #e37400; font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> Global Information</div>\n"
    },
    {
     "title": "Indicators (ms)",
     "type": "graph",
     "description": "# Indicators\nwith filter by\n\n* simulation = ```$simulation```",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "t≤$duration_1",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"mean\" <= $duration_1 and \"status\" = 'ok' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "$duration_1< t≤$duration_2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"mean\" > $duration_1 and \"mean\" <= $duration_2 and \"status\" = 'ok' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "t>$duration_2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"mean\" > $duration_2 and \"status\" = 'ok' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"status\" = 'ko' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 13, "w": 2, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "t ≤ $duration_1 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"mean\" <= $duration_1 and \"status\" = 'ok' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "$duration_1 ms < t ≤ $duration_2 ms",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"mean\" > $duration_1 and \"mean\" <= $duration_2 and \"status\" = 'ok' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "t > $duration_2 ms",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"mean\" > $duration_2 and \"status\" = 'ok' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" = '$simulation') and $timeFilter and \"status\" = 'ko' and \"request\" = 'allRequests' and (\"run\" =~ /^$run$/ or \"run\" = '') and (\"host\" =~ /^$host$/ or \"host\" = '')), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "STATISTICS",
     "type": "table-old",
     "description": "#### STATISTICS\nwith filter by\n\n* simulation = ```$simulation```\n* request =~ ```$request```",
     "gridPos": { "h": 13, "w": 16, "x": 8, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 3+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 3 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 0\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/ OR \"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 3+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 3 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 0\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/ OR \"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, level 3+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 3 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, %KO, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, %KO, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  \"KO\", \"% KO\", level 0\nSELECT (first(\"X\") + last(\"X\") - first(\"X\")) as \"KO\", last(\"X\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/ OR \"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 3+\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 3 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\"\n) GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 2\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\"\n) GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0, min, 50%, 75%, 95%, max, mean, std, level 1\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\"\n) GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 0\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/ OR \"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\"\n) GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
     "content": "<div style=\"font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> <span style=\"color: #e37400;\">Global Information</span> : Active Users</div>\n"
    },
    {
     "title": "Active Users along the Simulation",
     "type": "graph",
     "description": "*Active Users (Scenarios) along the Simulation* \n\nwith filter by\n* simulation =~ ```$simulation```\n* (user) scenario \n  * =~ ```$scenario```\n  * = ```allUsers```",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "repeat": "simulation",
     "yaxes": [
      { "format": "none", "label": "Concurent Users" }
     ],
     "targets": [
      {
       "alias": "Concurent Users",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"active\"-\"done\" FROM (SELECT mean(\"active\") AS \"active\", non_negative_derivative(last(\"done\"), 1s) AS \"done\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Concurent Users 2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"active\"-\"done\" FROM (SELECT mean(\"active\") AS \"active\", non_negative_derivative(last(\"done\"), 1s) AS \"done\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Active Users",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allUsers" }
       ]
      },
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$scenario$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"request\" fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$scenario$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time Percentiles over Time (OK)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "repeat": "simulation",
     "yaxes": [
      { "format": "ms", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$col",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT min(\"min\") AS \"min\", percentile(\"percentiles50\", 50) AS \"50%\", percentile(\"percentiles75\", 75) AS \"75%\", percentile(\"percentiles95\", 95) AS \"95%\", percentile(\"percentiles99\", 99) AS \"99%\", max(\"max\") AS \"max\"  FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok' AND \"simulation\" =~ /^$simulation$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"simulation\" fill(null)",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" },
         { "params": [ "50%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles95" ], "type": "field" },
         { "params": [ "95" ], "type": "percentile" },
         { "params": [ "95%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles99" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" },
         { "params": [ "99%" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles75" ], "type": "field" },
         { "params": [ "75" ], "type": "percentile" },
         { "params": [ "75%" ], "type": "alias" }
        ],
        [
         { "params": [ "min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "min" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"simulation\" fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allUsers" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
     "content": "<div style=\"font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> <span style=\"color: #e37400;\">Global Information</span> : Requests / sec</div>\n"
    },
    {
     "title": "Number of requests per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
     "repeat": "simulation",
     "yaxes": [
      { "format": "reqps", "label": "Number of requests" }
     ],
     "targets": [
      {
       "alias": "$col",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) AS \"All\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "All" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allUsers" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
     "content": "<div style=\"font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> <span style=\"color: #e37400;\">Global Information</span> : Responces / sec</div>\n"
    },
    {
     "title": "Number of responses per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "reqps", "label": "Number of responses" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"status\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"request\" = 'allUsers' AND \"simulation\" =~ /^$simulation$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allUsers" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "content": "<div style=\"color: #e37400; font-weight: bold; float: right; padding: 0; margin: 0; position: absolute; right: 0; z-index: -1; padding: 7px 50px; margin: 5px 5px 0 5px; font-size: 28px;\">$simulation</div>\n\n<div style=\"border-bottom: 7px #E37400 solid; padding: 10px 0 5px 0; margin: 0 5px; z-index: -1;\">\n<div style=\"background: #e37400; color: #fff; font-weight: bold; display: inline; margin: 0 10px 0 0; padding: 5px 15px 5px 25px; border-top-right-radius: 8px; border-top-left-radius: 8px; font-size: 14px;\">DETAILS</div>\n</div>"
    },
    {
     "title": "Response Time (Mean) over Time",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"mean\") FROM \"$archive\".\"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND (\"group\" = '0' OR \"group\" = '') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"request\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "[$tag_group1]  >  $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT mean(\"mean\") FROM \"$archive\".\"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" = '1' AND \"group1\" =~ /^$group1$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"request\", \"group1\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" }
       ]
      },
      {
       "alias": "[$tag_group1]  >  [$tag_group2]  >  $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT mean(\"mean\") FROM \"$archive\".\"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"request\", \"group1\", \"group2\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" },
        { "condition": "AND", "key": "group2", "operator": "=~", "value": "/^$group2$/" }
       ]
      },
      {
       "alias": "[$tag_group1]  >  [$tag_group2]  >  [$tag_group3] > $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "group3" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT mean(\"mean\") FROM \"$archive\".\"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" = '3' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"request\", \"group1\", \"group2\", \"group3\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" },
        { "condition": "AND", "key": "group2", "operator": "=~", "value": "/^$group2$/" },
        { "condition": "AND", "key": "group3", "operator": "=~", "value": "/^$group3$/" }
       ]
      },
      {
       "alias": "[$tag_group1]",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"mean\")), 1s) FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" = '1' AND \"group1\" =~ /^$group1$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"group1\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" }
       ]
      },
      {
       "alias": "[$tag_group1]  >  [$tag_group2]",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"mean\")), 1s) FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"group1\", \"group2\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" },
        { "condition": "AND", "key": "group2", "operator": "=~", "value": "/^$group2$/" }
       ]
      },
      {
       "alias": "[$tag_group1]  >  [$tag_group2]  >  [$tag_group3]",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "group3" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"mean\")), 1s) FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" = '3' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"group1\", \"group2\", \"group3\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" },
        { "condition": "AND", "key": "group2", "operator": "=~", "value": "/^$group2$/" },
        { "condition": "AND", "key": "group3", "operator": "=~", "value": "/^$group3$/" }
       ]
      },
      {
       "alias": "[$tag_group1]  >  [$tag_group2]  >  [$tag_group3] > ... > $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "group3" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT mean(\"mean\") FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND \"group\" <> '3' AND \"group\" <> '2' AND \"group\" <> '1' AND \"group\" <> '' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/ AND \"request\" =~ /^$request$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"group1\", \"group2\", \"group3\", \"request\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "group", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "group1", "operator": "=~", "value": "/^$group1$/" },
        { "condition": "AND", "key": "group2", "operator": "=~", "value": "/^$group2$/" },
        { "condition": "AND", "key": "group3", "operator": "=~", "value": "/^$group3$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allUsers" }
       ]
      }
     ]
    },
    {
     "title": "STATISTICS",
     "type": "yesoreyeram-boomtable-panel",
     "description": "#### STATISTICS\nwith filter by\n\n* simulation = ```$simulation```\n* request =~ ```$request```",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 4+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 3\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 0\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "<b>Global Information</b>:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, Global Information\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 4+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 3\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"= '3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 0\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "<b>Global Information</b>:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, Global Information\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, % KO, level 4+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, % KO, level 3\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\"  FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, %KO, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, %KO, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  \"KO\", \"% KO\", level 0\nSELECT (first(\"X\") + last(\"X\") - first(\"X\")) as \"KO\", last(\"X\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "<b>Global Information</b>:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  \"KO\", \"% KO\", Global Information\nSELECT (first(\"X\") + last(\"X\") - first(\"X\")) as \"KO\", last(\"X\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 4+\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\"\n) GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 3\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"='3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\"\n) GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 2\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\"\n) GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0, min, 50%, 75%, 95%, max, mean, std, level 1\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\"\n) GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 0\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\"\n) GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "<b>Global Information</b>:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, Global Information\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" = 'allRequests') AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\"\n) GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "request",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
     "content": "\n<div style=\"border-bottom: 7px #E37400 solid; padding: 10px 0 5px 0; margin: 0 5px; z-index: -1;\">\n</div>\n<div style=\"color: #e37400; font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt;</span> $request</div> "
    },
    {
     "title": "Indicators",
     "type": "graph",
     "description": "# Indicators\nwith filter by\n\n* simulation = ```$simulation```",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "t ≤ $duration_1 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"mean\" <= $duration_1  AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "mean", "operator": "<", "value": "$duration_1" }
       ]
      },
      {
       "alias": "$duration_1 ms < t ≤ $duration_2 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"mean\" > $duration_1 AND \"mean\" <= $duration_2   AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "$duration_1 ms < t < $duration_2 ms"
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "mean", "operator": ">", "value": "$duration_1" },
        { "condition": "AND", "key": "mean", "operator": "<", "value": "$duration_2" }
       ]
      },
      {
       "alias": "t > $duration_2 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") AS \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"mean\" > $duration_2 AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "mean", "operator": ">", "value": "$duration_2" }
       ]
      },
      {
       "alias": "failed",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") AS \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ko'  AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE \"simulation\" =~ /^$simulation$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 2, "x": 6, "y": 14 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "alias": "t ≤ $duration_1 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"mean\" <= $duration_1  AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "mean", "operator": "<", "value": "$duration_1" }
       ]
      },
      {
       "alias": "$duration_1 ms < t ≤ $duration_2 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"mean\" > $duration_1 AND \"mean\" <= $duration_2   AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "$duration_1 ms < t < $duration_2 ms"
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "mean", "operator": ">", "value": "$duration_1" },
        { "condition": "AND", "key": "mean", "operator": "<", "value": "$duration_2" }
       ]
      },
      {
       "alias": "t > $duration_2 ms",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") AS \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"mean\" > $duration_2 AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "mean", "operator": ">", "value": "$duration_2" }
       ]
      },
      {
       "alias": "failed",
       "measurement": "gatling",
       "query": "SELECT max(X) FROM (SELECT sum(\"count\") AS \"X\" FROM \"$archive\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ko'  AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter fill(0)), (SELECT last(\"count\")-last(\"count\") as \"X\" FROM \"$archive\".gatling WHERE $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=", "value": "$simulation" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "$request" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    { "title": "STATISTICS", "type": "text", "gridPos": { "h": 1, "w": 16, "x": 8, "y": 14 }, "content": "\n\n\n\n" },
    {
     "title": "Executions",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- Total, OK, KO\nSELECT \"StatusCode\" FROM\n(SELECT X+10 as \"StatusCode\"  FROM(SELECT last(\"zero\")+first(\"zero\")-last(\"zero\") as \"X\" FROM(SELECT last(\"count\")-last(\"count\") as \"zero\" FROM \"$archive\".\"gatling\" where \"status\"='all' GROUP BY \"status\") GROUP BY \"status\")),\n(SELECT X+20 as \"StatusCode\"  FROM(SELECT last(\"zero\")+first(\"zero\")-last(\"zero\") as \"X\" FROM(SELECT last(\"count\")-last(\"count\") as \"zero\" FROM \"$archive\".\"gatling\" where \"status\"='ok' GROUP BY \"status\") GROUP BY \"status\")),\n(SELECT X+30 as \"StatusCode\"  FROM(SELECT last(\"zero\")+first(\"zero\")-last(\"zero\") as \"X\" FROM(SELECT last(\"count\")-last(\"count\") as \"zero\" FROM \"$archive\".\"gatling\" where \"status\"='ko' GROUP BY \"status\") GROUP BY \"status\")) \nGROUP BY \"status\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"Total\", \"Total\"/$testDuration as \"Mean cnt/s\"\nFROM (\n  SELECT last(\"X\")+first(\"X\")-last(\"X\") as \"Total\"\n  FROM (\n    SELECT sum(\"count\") as \"X\"\n    FROM \"$archive\".\"gatling\"\n    WHERE (\"request\" =~ /^$request$/ AND \"simulation\" =~ /^$simulation$/ AND (\"group\" = '0' OR \"group\" = '' OR (\"group\" = '1' AND \"group1\" =~ /^$group1$/) OR (\"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/) OR (\"group\"!='' AND \"group\"!='0'  AND \"group\"!='1' AND \"group\"!='2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/)) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY \"status\" fill(null)\n  ) GROUP BY \"status\"\n) GROUP BY \"status\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Time (ms)",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- Total, OK, KO\nSELECT \"StatusCode\" FROM\n(SELECT X+10 as \"StatusCode\"  FROM(SELECT last(\"zero\")+first(\"zero\")-last(\"zero\") as \"X\" FROM(SELECT last(\"count\")-last(\"count\") as \"zero\" FROM \"$archive\".\"gatling\" where \"status\"='all' GROUP BY \"status\") GROUP BY \"status\")),\n(SELECT X+20 as \"StatusCode\"  FROM(SELECT last(\"zero\")+first(\"zero\")-last(\"zero\") as \"X\" FROM(SELECT last(\"count\")-last(\"count\") as \"zero\" FROM \"$archive\".\"gatling\" where \"status\"='ok' GROUP BY \"status\") GROUP BY \"status\")),\n(SELECT X+30 as \"StatusCode\"  FROM(SELECT last(\"zero\")+first(\"zero\")-last(\"zero\") as \"X\" FROM(SELECT last(\"count\")-last(\"count\") as \"zero\" FROM \"$archive\".\"gatling\" where \"status\"='ko' GROUP BY \"status\") GROUP BY \"status\"))\nGROUP BY \"status\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \n  last(\"Min\")+first(\"Min\")-last(\"Min\") as \"Min\",\n  last(\"50th pct\")+first(\"50th pct\")-last(\"50th pct\") as \"50th pct\",\n  last(\"75th pct\")+first(\"75th pct\")-last(\"75th pct\") as \"75th pct\",\n  last(\"95th pct\")+first(\"95th pct\")-last(\"95th pct\") as \"95th pct\",\n  last(\"99th pct\")+first(\"99th pct\")-last(\"99th pct\") as \"99th pct\",\n  last(\"Max\")+first(\"Max\")-last(\"Max\") as \"Max\",\n  last(\"Mean\")+first(\"Mean\")-last(\"Mean\") as \"Mean\",\n  last(\"Std dev\")+first(\"Std dev\")-last(\"Std dev\") as \"Std dev\"\nFROM (\nSELECT min(\"min\") as \"Min\", percentile(\"percentiles50\", 50) as \"50th pct\", percentile(\"percentiles75\", 75) as \"75th pct\", percentile(\"percentiles95\", 95) as \"95th pct\", percentile(\"percentiles99\", 99) as \"99th pct\", max(\"max\") as \"Max\", ceil(mean(\"mean\")) as \"Mean\", percentile(\"stdDev\", 95) as \"Std dev\"\nFROM \"$archive\".\"gatling\"\nWHERE (\"request\" =~ /^$request$/ AND \"simulation\" =~ /^$simulation$/ AND (\"group\" = '0' OR \"group\" = '' OR (\"group\" = '1' AND \"group1\" =~ /^$group1$/) OR (\"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/) OR (\"group\"!='' AND \"group\"!='1' AND \"group\"!='2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/)) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY \"status\" fill(null)\n), \n(SELECT \"X\" as \"Min\", \"X\" as \"50th pct\", \"X\" as \"75th pct\", \"X\" as \"95th pct\", \"X\" as \"99th pct\", \"X\" as \"Max\", \"X\" as \"Mean\", \"X\" as \"Std dev\"\nFROM ( \nSELECT last(\"count\")-last(\"count\")-10 as \"X\" FROM \"$archive\".\"gatling\" GROUP BY \"status\"\n) GROUP BY \"status\"\n)\nGROUP BY \"status\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 20 },
     "targets": [
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 4+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 3\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  Total, level 0\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"Total\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 4+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 3\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"= '3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  OK, level 0\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"OK\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ok') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, % KO, level 4+\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, % KO, level 3\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\"  FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\") GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, %KO, level 2\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\") GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  KO, %KO, level 1\nSELECT (first(\"T\") + last(\"T\") - first(\"T\")) as \"KO\", last(\"T\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"T\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\") GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "-- time = 0,  \"KO\", \"% KO\", level 0\nSELECT (first(\"X\") + last(\"X\") - first(\"X\")) as \"KO\", last(\"X\")/$Total as \"% KO\" FROM (SELECT sum(\"count\") as \"X\" FROM \"$archive\".\"gatling\" WHERE (\"status\" = 'ko') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\") GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > ... > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 4+\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"::integer >= 4 AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\"\n) GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_group3 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 3\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\"='3' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/ AND \"group3\"=~/^$group3$/) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\", \"group3\"\n) GROUP BY \"request\", \"group1\", \"group2\", \"group3\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_group1 > $tag_group2 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 2\nSELECT\n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='2' AND \"group1\"=~/^$group1$/ AND \"group2\"=~/^$group2$/)) AND $timeFilter GROUP BY \"request\", \"group1\", \"group2\"\n) GROUP BY \"request\", \"group1\", \"group2\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_group1 > $tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0, min, 50%, 75%, 95%, max, mean, std, level 1\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND ((\"group\"='1' AND \"group1\"=~/^$group1$/)) AND $timeFilter GROUP BY \"request\", \"group1\"\n) GROUP BY \"request\", \"group1\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_request:::$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "-- time = 0,  min, 50%, 75%, 95%, max, mean, std, level 0\nSELECT \n  (first(\"Min\")+last(\"Min\")-first(\"Min\")) as \"Min\",\n  (first(\"50th pct\")+last(\"50th pct\")-first(\"50th pct\")) as \"50th pct\",\n  (first(\"75th pct\")+last(\"75th pct\")-first(\"75th pct\")) as \"75th pct\",\n  (first(\"95th pct\")+last(\"95th pct\")-first(\"95th pct\")) as \"95th pct\",\n  (first(\"99th pct\")+last(\"99th pct\")-first(\"99th pct\")) as \"99th pct\",\n  (first(\"Max\")+last(\"Max\")-first(\"Max\")) as \"Max\",\n  (first(\"Mean\")+last(\"Mean\")-first(\"Mean\")) as \"Mean\",\n  (first(\"Std dev\")+last(\"Std dev\")-first(\"Std dev\")) as \"Std dev\"\nFROM (\n  SELECT \n    min(\"min\") as \"Min\",\n    percentile(\"percentiles50\", 50) as \"50th pct\",\n    percentile(\"percentiles75\", 75) as \"75th pct\",\n    percentile(\"percentiles95\", 95) as \"95th pct\",\n    percentile(\"percentiles99\", 99) as \"99th pct\",\n    max(\"max\") as \"Max\",\n    mean(\"mean\") as \"Mean\",\n    percentile(\"stdDev\", 95) as \"Std dev\"\n  FROM \n    \"$archive\".\"gatling\" \n  WHERE \n    (\"status\" = 'all') AND (\"simulation\" =~ /^$simulation$/) AND (\"request\" =~ /^$request$/) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '')  AND $timeFilter GROUP BY \"request\"\n) GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
     "content": "<div style=\"font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> <span style=\"color: #e37400;\">$request</span> : Response Time</div>\n\n"
    },
    {
     "title": "Response Time Percentiles over Time (OK)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$col",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT min(\"min\") AS \"min\", percentile(\"percentiles50\", 50) AS \"50%\", percentile(\"percentiles75\", 75) AS \"75%\", percentile(\"percentiles95\", 95) AS \"95%\", percentile(\"percentiles99\", 99) AS \"99%\", max(\"max\") AS \"max\"  FROM \"$archive\".\"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'ok' AND \"simulation\" =~ /^$simulation$/ AND (\"group\" = '0' OR \"group\" = '' OR (\"group\" = '1' AND \"group1\" =~ /^$group1$/) OR (\"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/) OR (\"group\"!='' AND \"group\"!='1' AND \"group\"!='2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/)) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"simulation\" fill(null)",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" },
         { "params": [ "50%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles95" ], "type": "field" },
         { "params": [ "95" ], "type": "percentile" },
         { "params": [ "95%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles99" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" },
         { "params": [ "99%" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles75" ], "type": "field" },
         { "params": [ "75" ], "type": "percentile" },
         { "params": [ "75%" ], "type": "alias" }
        ],
        [
         { "params": [ "min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "min" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g), \"simulation\" fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allUsers" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
     "content": "<div style=\"font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> <span style=\"color: #e37400;\">$request</span> : Requests / sec</div>\n"
    },
    {
     "title": "Number of requests per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "reqps", "label": "Number of requests" }
     ],
     "targets": [
      {
       "alias": "$col",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) AS \"All\" FROM \"$archive\".\"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'all' AND \"simulation\" =~ /^$simulation$/ AND (\"group\" = '0' OR \"group\" = '' OR (\"group\" = '1' AND \"group1\" =~ /^$group1$/) OR (\"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/) OR (\"group\"!='' AND \"group\"!='1' AND \"group\"!='2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/)) AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "All" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"$archive\".\"gatling.users\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" = 'allUsers' AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allUsers" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
     "content": "<div style=\"font-weight: bold; padding: 0; margin: 0; right: 0; padding: 7px 0px; margin: 5px 5px 0 5px; font-size: 18px;\"><span style=\"color: #D1D1CE;\">&gt; </span> <span style=\"color: #e37400;\">$request</span> : Responces / sec</div>"
    },
    {
     "title": "Number of responses per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "reqps", "label": "Number of responses" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) FROM \"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"simulation\" =~ /^$simulation$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '') AND (\"group\" = '0' OR \"group\" = '' OR (\"group\" = '1' AND \"group1\" =~ /^$group1$/) OR (\"group\" = '2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/) OR (\"group\"!='' AND \"group\"!='1' AND \"group\"!='2' AND \"group1\" =~ /^$group1$/ AND \"group2\" =~ /^$group2$/ AND \"group3\" =~ /^$group3$/))) AND $timeFilter GROUP BY time($g), \"status\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"active\")), 1s) AS \"Active Users\" FROM \"gatling.users\" WHERE (\"request\" = 'allUsers' AND \"simulation\" =~ /^$simulation$/ AND (\"run\" =~ /^$run$/ OR \"run\" = '') AND (\"host\" =~ /^$host$/ OR \"host\" = '')) AND $timeFilter GROUP BY time($g) fill(null)",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Active Users" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allUsers" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}